services:
  bash-language-server:
    image: lspcontainers/bash-language-server:build
    build:
      context: bash-language-server
      dockerfile: Dockerfile
  docker-language-server:
    image: lspcontainers/docker-language-server:build
    build:
      context: docker-langserver
      dockerfile: Dockerfile
  gopls:
    image: lspcontainers/gopls:build
    build:
      context: gopls
      dockerfile: Dockerfile
  lua-language-server:
    image: lspcontainers/lua-language-server:build
    build:
      context: lua-language-server
      dockerfile: Dockerfile
  typescript-language-server:
    image: lspcontainers/typescript-language-server:build
    build:
      context: typescript-language-server
      dockerfile: Dockerfile
  yaml-language-server:
    image: lspcontainers/yaml-language-server:build
    build:
      context: yaml-language-server
      dockerfile: Dockerfile
version: "3.8"
