version: "3.8"

# docker-compose build
services:
  node_base:
    image: lspcontainers/node_base:14
    build:
      context: node_base
      dockerfile: Dockerfile
  yaml:
    image: lspcontainers/yaml-language-server:${yamlls_ver}
    depends_on:
      - node_base
    build:
      context: yaml-language-server
      dockerfile: Dockerfile
      args:
        VERSION: ${yamlls_ver}
