name: Push LSP Docker Images

on:
  push:
    branches: [ main ]

jobs:
  build_and_push:
    name: Build and push ${{ matrix.context }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - context: bashls
            tag: bash-language-server
            version: 1.17.0

          - context: dockerls
            tag: docker-language-server
            version: 0.4.1

          - context: gopls
            tag: gopls
            version: 0.6.11

          - context: pylsp
            tag: python-lsp
            version: 1.0.1

          - context: pyright
            tag: pyright-langserver
            version: 1.1.137

          - context: rust_analyzer
            tag: rust-analyzer
            version: "2021-05-03"

          - context: sumneko_lua
            tag: lua-language-server
            version: 1.21.1

          - context: svelteserver
            tag: svelte-language-server
            version: 0.13.7

          - context: terraformls
            tag: terraform-ls
            version: 0.16.3

          - context: tsserver
            tag: typescript-language-server
            version: 0.5.1

          - context: yamlls
            tag: yaml-language-server
            version: 0.18.0

          - context: vuels
            tag: vue-language-server
            version: 0.7.2
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          build-args: |
            VERSION=${{ matrix.version }}
          context: servers/${{ matrix.context }}
          push: true
          tags: lspcontainers/${{ matrix.tag }}:${{ matrix.version }}
